// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx0KpjqGA_1l6an-4WtJGbaHbk8VRCey8',
    appId: '1:892900617371:web:9201c4af408db0e0172a3e',
    messagingSenderId: '892900617371',
    projectId: 'domicert-53795',
    authDomain: 'domicert-53795.firebaseapp.com',
    storageBucket: 'domicert-53795.firebasestorage.app',
    measurementId: 'G-LY8DZ4H0R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAYMJJNbWtzj4NC8R8dgPj7qUexa4JnyM',
    appId: '1:892900617371:android:22f65220ad91a9b1172a3e',
    messagingSenderId: '892900617371',
    projectId: 'domicert-53795',
    storageBucket: 'domicert-53795.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwxJaNNcdwX_b63jk-H64TiUjmUtieHe0',
    appId: '1:892900617371:ios:693e1c1f38da354d172a3e',
    messagingSenderId: '892900617371',
    projectId: 'domicert-53795',
    storageBucket: 'domicert-53795.firebasestorage.app',
    androidClientId: '892900617371-14f4cvimmviftriiqkat5i0980aq4aqh.apps.googleusercontent.com',
    iosClientId: '892900617371-7uuomin2vm1ipcu6utghs1u53oe1etiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.homepass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwxJaNNcdwX_b63jk-H64TiUjmUtieHe0',
    appId: '1:892900617371:ios:693e1c1f38da354d172a3e',
    messagingSenderId: '892900617371',
    projectId: 'domicert-53795',
    storageBucket: 'domicert-53795.firebasestorage.app',
    androidClientId: '892900617371-14f4cvimmviftriiqkat5i0980aq4aqh.apps.googleusercontent.com',
    iosClientId: '892900617371-7uuomin2vm1ipcu6utghs1u53oe1etiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.homepass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx0KpjqGA_1l6an-4WtJGbaHbk8VRCey8',
    appId: '1:892900617371:web:fd88bce39d641c88172a3e',
    messagingSenderId: '892900617371',
    projectId: 'domicert-53795',
    authDomain: 'domicert-53795.firebaseapp.com',
    storageBucket: 'domicert-53795.firebasestorage.app',
    measurementId: 'G-QZFJ1TB13F',
  );
}
